# For info on how to update this file see: https://github.com/marketplace/actions/repo-file-sync-action#%EF%B8%8F-sync-configuration

group:
  - files:
      - source: .github/workflows/
        dest: .github/workflows/
        exclude: |
          send-updates.yml
          test-send-updates.yml
          starting-course.yml
          release-notes.yml
      - source: .github/ISSUE_TEMPLATE/course-problem-report.md
        dest: .github/ISSUE_TEMPLATE/course-problem-report.md
      - source: .github/ISSUE_TEMPLATE/course-content-add.md
        dest: .github/ISSUE_TEMPLATE/course-content-add.md
      - source: scripts/spell-check.R
        dest: scripts/spell-check.R
      - source: scripts/url-check.R
        dest: scripts/url-check.R
      - source: scripts/quiz-check.R
        dest: scripts/quiz-check.R
      - source: scripts/git_repo_check.R
        dest: scripts/git_repo_check.R
      - source: scripts/make_screenshots.R
        dest: scripts/make_screenshots.R
      - source: code_of_conduct.md
        dest: code_of_conduct.md
      - source: style-sets
        dest: style-sets
      - source: assets/box_images/
        dest: assets/box_images/
      - source: assets/AnVIL_style/
        dest: assets/AnVIL_style/
        deleteOrphaned: true
      - source: assets/toc_close.css
        dest: assets/toc_close.css
      - source: _output.yml
        dest: _output.yml
      - source: scripts/anvil_repo_check.R
        dest: scripts/anvil_repo_check.R
      - source: scripts/anvil_repo_table.R
        dest: scripts/anvil_repo_table.R
  # Repositories to receive changes
    repos: |
      jhudsl/AnVIL_Book_WDL
###ADD NEW REPO HERE following the format above#
